const converterListActionTypes = {
  ADD_CURRENCY: "ADD_CURRENCY",
  CLEAR_CURRENCY: "CLEAR_CURRENCY",
  REMOVE_CURRENCY: "REMOVE_CURRENCY",
  HANDLE_INPUT: "HANDLE_INPUT",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  HANDLE_SWAP: "HANDLE_SWAP",
  REQUEST_RATES_PENDING: "REQUEST_RATES_PENDING",
  REQUEST_RATES_SUCCESS: "REQUEST_RATES_SUCCESS",
  REQUEST_RATES_FAILED: "REQUEST_RATES_FAILED"
};

export default converterListActionTypes;
